### ISSUE TITLE
Switch over to Brett's design

### ISSUE THREAD

**Issue by KrabbiePatty** [CSAllenISD/2023-ISP-ModelScheduler#107]
I think that we should switch over to using Brett's design because it has an overall better design.
![Image](https://user-images.githubusercontent.com/89479023/218548992-3e87cf32-6ee1-4d70-90bd-ba4f1f167b52.PNG)

**Comment by Reynard-G** [comment]
Agreed

**Comment by June3333** [comment]
I agree that it has a better design, but period 1 and 8 has to be blocked

**Comment by IsaacDaKing** [comment]
I agree with June. Maybe just to speed things up we should port over Brett's design, then edit it. Rather than keeping it separate and editing it from there. Will help if multiple people are able to contribute to it in the repository, someone should definitely talk to @nalyd1369 and the Product Managers about this.

**Comment by GetJumpedOn95** [comment]
I concur
