### ISSUE TITLE
Attention! Join the Discord server if your are able to.

### ISSUE THREAD

**Issue by ryanhallock** [CSAllenISD/2023-ISP-ModelScheduler#53]
There should be a link to join the Discord server on the sheet located [here](https://docs.google.com/spreadsheets/d/1FkO3ScF-8j51DM8966VqbcL8iOl_KYXpkZRe2dFMhDA/edit?usp=sharing).

If you cannot use the Discord server or don't have access to the sheet, please let me know by replying to this issue.

**Comment by IsaacDaKing** [comment]
Unfortunately, I cannot be present on the discord seeing as I am currently grounded, I'll rely on Github issues for communication. If something is more urgent, I recommend emailing me directly, because GitHub notifications are delayed (hopefully we won't be in a circumstance in which we're too worried about time).
